/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'onlineStatus' : IDL.Bool,
});
export const Time = IDL.Int;
export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'recipient' : IDL.Principal,
  'sender' : IDL.Principal,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFriend' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'endCall' : IDL.Func([], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ChatMessage)],
      ['query'],
    ),
  'getFriendsList' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserStatus' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Bool)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFriend' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'startCall' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'onlineStatus' : IDL.Bool,
  });
  const Time = IDL.Int;
  const ChatMessage = IDL.Record({
    'content' : IDL.Text,
    'recipient' : IDL.Principal,
    'sender' : IDL.Principal,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFriend' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'endCall' : IDL.Func([], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'getFriendsList' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserStatus' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Bool)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFriend' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'startCall' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };